name: Release Hello World

on:
  release:
    types: [published]

jobs:
  release:
    name: Create Release and Upload File
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create file with dynamic content
        run: |
          echo "Hello, World!" > file.txt
          echo "Release: ${{ github.event.release.tag_name }}" >> file.txt
          echo "Published at: ${{ github.event.release.published_at }}" >> file.txt
          echo "Generated at: $(date -u)" >> file.txt

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: file.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
